<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150624110209 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE sandstorm_newsletter_domain_model_unsubscribelist (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup ADD unsubscribelist VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup ADD CONSTRAINT FK_B1DF4D42EF881977 FOREIGN KEY (unsubscribelist) REFERENCES sandstorm_newsletter_domain_model_unsubscribelist (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B1DF4D42EF881977 ON sandstorm_newsletter_domain_model_receivergroup (unsubscribelist)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup DROP FOREIGN KEY FK_B1DF4D42EF881977");
		$this->addSql("DROP TABLE sandstorm_newsletter_domain_model_unsubscribelist");
		$this->addSql("DROP INDEX IDX_B1DF4D42EF881977 ON sandstorm_newsletter_domain_model_receivergroup");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup DROP unsubscribelist");
	}
}