<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150528091835 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receiversource ADD sourcefile VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receiversource ADD CONSTRAINT FK_2C8A76F990002AAB FOREIGN KEY (sourcefile) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_2C8A76F990002AAB ON sandstorm_newsletter_domain_model_receiversource (sourcefile)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receiversource DROP FOREIGN KEY FK_2C8A76F990002AAB");
		$this->addSql("DROP INDEX IDX_2C8A76F990002AAB ON sandstorm_newsletter_domain_model_receiversource");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receiversource DROP sourcefile");
	}
}