<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150527130855 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE sandstorm_newsletter_domain_model_receiversource (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, sourcefilename VARCHAR(255) NOT NULL, dimensionfilter LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup ADD receiversource VARCHAR(40) DEFAULT NULL, DROP name, DROP sourcefilename, DROP dimensionfilter");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup ADD CONSTRAINT FK_B1DF4D4214D6C708 FOREIGN KEY (receiversource) REFERENCES sandstorm_newsletter_domain_model_receiversource (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B1DF4D4214D6C708 ON sandstorm_newsletter_domain_model_receivergroup (receiversource)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup DROP FOREIGN KEY FK_B1DF4D4214D6C708");
		$this->addSql("DROP TABLE sandstorm_newsletter_domain_model_receiversource");
		$this->addSql("DROP INDEX IDX_B1DF4D4214D6C708 ON sandstorm_newsletter_domain_model_receivergroup");
		$this->addSql("ALTER TABLE sandstorm_newsletter_domain_model_receivergroup ADD name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD sourcefilename VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD dimensionfilter LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:array)', DROP receiversource");
	}
}